### ISSUE TITLE
Change colors of the button under Logo to be consistent with the color scheme

### ISSUE THREAD

**Issue by manastalukdar** [manastalukdar/learning-computer-science#60]
Change the color of the button ("resources/images/logo/button LCS color") so that the `L` is grey and the background is white. I would like this to be consistent with the color scheme in other images ("resources\images\logo\icon LCS color" and "resources\images\logo\Logo LCS color"), where the `L` is grey.

@Pelikens can you please look into this.

**Comment by Pelikens** [comment]
Hello, https://drive.google.com/file/d/12bu7sHy4vdeK9A_-_sHjPs5P-fZ2z1A8/view?usp=sharing

**Comment by manastalukdar** [comment]
That looks great. Could you please provide the different file options for it ("high res.png", "low res.png", .ai, .psd and .svg).
